config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  get '/sign_up', to: 'user#sign_up', as: :sign_up
  post '/sign_up', to: 'user#authenticate'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :email_address, :first_name, :last_name, :dob, :username, :password_hash, presence: true

  
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/user_controller.rb
# frozen_string_literal: true

class UserController < ApplicationController

  def sign_up
    @sign_up_form = SignUpForm.new
  end

  def authenticate
    @sign_up_form = SignUpForm.new(sign_up_params)
    set_dob = DateTime.new(params['year'].to_i, params['month'].to_i, params['day'].to_i)
    User.create!(
      email_address: params['email_address'],
      username: params['username'],
      first_name: params['first_name'],
      last_name: params['last_name'],
      dob: set_dob,
      password: Password.create(params['password'])
    )
    redirect_to root_path
  end

private

  def sign_up_params
    params.require(:sign_up_form).permit(:email_address, :username, :first_name,
       :last_name, :day, :month, :year, :password, :confirm_password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light border border-secondary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Sign Up', sign_up_path , class: "nav-link" %>
        </li>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-secondary" type="submit">Search</button>
      </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>Base rails app</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>

    <%= render "layouts/header" %>
    <div>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>

  </body>


</html>

app/views/user/_form.html.erb
<%= form_with_model(model: @sign_up_form, url: sign_up_path, method: :post) do |form| %>

  <div class="field form-group">
    <% form.label :email_address %>
    <%= form.text_field :email_address, class:"form-control", placeholder:"Email Address", id:"#email_address" %>
  </div>

  <div class="field form-group">
    <% form.label :username %>
    <%= form.text_field :username, class:"form-control", placeholder:"Username", id:'#username' %>
  </div>

  <div class="field form-group">
    <% form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name", id:"#first_name"%>
  </div>

  <div class="field form-group">
    <% form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name", id:'#last_name' %>
  </div>

  <div class="field form-group">
    <% form.label :day %>
    <%= form.text_field :day, class:"form-control", placeholder:"Day", id:'#day' %>
    <% form.label :month %>
    <%= form.text_field :month, class:"form-control", placeholder:"Month", id:'#month' %>
    <% form.label :year %>
    <%= form.text_field :year, class:"form-control", placeholder:"Year", id:'#year' %>
  </div>

  <div class="field form-group">
    <% form.label :password %>
    <%= form.password_field :password, class:"form-control", placeholder:"Password", id:'#password' %>
  </div>

  <div class="field form-group">
    <% form.label :confirm_password %>
    <%= form.password_field :confirm_password, class:"form-control", placeholder:"Confirm Password", id:'#confirm_password'%>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-secondary', value:"Create Account" %>
  </div>
<% end %>

app/views/user/sign_up.html.erb
<h1>Add New Account</h1>
<br>

<%= render 'form', user: @user %>